[build-system]
requires = ["uv_build>=0.11.29,<0.12"]
build-backend = "uv_build"

[project]
name = "llm_utils"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "a2a-sdk[fastapi,mysql]>=1.1.0",
    "boto3>=1.42.49",
    "browser-use>=0.13.4",
    "ddgs>=9.10.0",
    "dill>=0.4.1",
    "docling>=2.93.0",
    "docling-core[chunking-openai]>=2.75.0",
    "fastapi[standard]>=0.128.0",
    "filetype>=1.2.0",
    "fsspec[s3]>=2026.2.0",
    "httpx>=0.28.1",
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.0.7",
    "llama-index-embeddings-openai-like>=0.3.1",
    "llama-index-llms-openai>=0.7.8",
    "llama-index-llms-openai-like>=0.7.2",
    "llama-index-node-parser-docling>=0.4.2",
    "llama-index-readers-docling>=0.4.2",
    "llama-index-readers-file>=0.6.0",
    "llama-index-vector-stores-elasticsearch",
    "markdownify>=1.2.2",
    "nats-py>=2.15.0",
    "openai>=2.16.0",
    "playwright>=1.60.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "pymongo>=4.17.0",
    "python-multipart>=0.0.22",
    "qdrant-client>=1.18.0",
    "sqlalchemy[asyncio]>=2.0.51",
]
